version: 0.2

phases:
  install:
    commands:
      - npm install -g npm@latest # NPM'nin en son sürümünü yükle
      - npm install # Projenin bağımlılıklarını yükle
  build:
    commands:
      - npm run build -- --configuration production
  post_build:
    commands:
      - aws s3 sync dist/epam-interview/browser s3://epam-interview-bucket --delete # Build sonucunu S3'e yükleyin
