version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - npm install
      - npm run build --configuration production
  post_build:
    commands:
      - aws s3 sync dist/epam-interview s3://epam-interview-bucket --delete
artifacts:
  files:
    - '**/*'
