version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
  build:
    commands:
      - npm install
      - npm run build --configuration production
  post_build:
    commands:
      - aws s3 sync dist/epam-interview/browser s3://epam-interview-bucket --delete
